### ISSUE TITLE
[REQUEST] Update to TypeWriter0.4.1 And Ady-2.0-36+

### ISSUE THREAD

**Issue by Yurium7** [ahdg6/TypeWriter-Adapter#1]
The current version of the adapter is malfunctioning, requesting an update

**Comment by ahdg6** [comment]
I will take a look when I have time

**Comment by ahdg6** [comment]
有 jar 吗，ady 的

**Comment by ahdg6** [comment]
哥们，最新版开发者文档是私有的，不公开看不了，你可以让坏黑仿造 citizen 插件的适配器支持一下呢，无能为力，这里的适配器是去年的，TypeWriter 大变样了就不要参考这里的代码了

**Comment by Yurium7** [comment]
https://a.ptms.ink/docs/start/dev/install 这个文档也不行吗?

**Comment by ahdg6** [comment]
这里真的有在更新吗，你发的这个文档就是 snapshot-1 的，https://docs.ptms.ink/document/index?document_id=35 这里才是最新的
